//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestion_Agences_Location.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOCAUX
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LOCAUX()
        {
            this.CONTRATs = new HashSet<CONTRAT>();
            this.TRAVEAUX = new HashSet<TRAVEAU>();
        }
    
        public int IDLOCAUX { get; set; }
        public string NOM { get; set; }
        public string ADRESSE { get; set; }
        public int IDTYPE { get; set; }
        public int SUPERFICIER { get; set; }
        public string DESCRIPTION { get; set; }
        public double PRIX { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CONTRAT> CONTRATs { get; set; }
        public virtual TYPE TYPE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TRAVEAU> TRAVEAUX { get; set; }
    }
}
