//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestion_Agences_Location.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Gestion_Agence_LocationEntities : DbContext
    {
        public Gestion_Agence_LocationEntities()
            : base("name=Gestion_Agence_LocationEntities")
        {
            this.Configuration.LazyLoadingEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    


        public virtual DbSet<Agence> Agences { get; set; }
        public virtual DbSet<CLIENT> CLIENTs { get; set; }
        public virtual DbSet<CONTRAT> CONTRATs { get; set; }
        public virtual DbSet<LOCAUX> LOCAUXes { get; set; }
        public virtual DbSet<Responsable> Responsables { get; set; }
        public virtual DbSet<TRAVEAU> TRAVEAUX { get; set; }
        public virtual DbSet<TYPE> TYPEs { get; set; }
        public virtual DbSet<Ville> Villes { get; set; }
    }
}
