//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestion_Agences_Location.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Responsable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Responsable()
        {
            this.Agences = new HashSet<Agence>();
        }
    
        public int IDRESPONSABLE { get; set; }
        public string NOM_PRENOM { get; set; }
        public string TELE { get; set; }
        public int IDVILLE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Agence> Agences { get; set; }
        public virtual Ville Ville { get; set; }
    }
}
