//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestion_Agences_Location.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRAVEAU
    {
        public int IDTRAVEAUX { get; set; }
        public System.DateTime DATE_TRAVEAUX { get; set; }
        public int IDLOCAUX { get; set; }
    
        public virtual LOCAUX LOCAUX { get; set; }
    }
}
